\c contrib_regression_utf8

-- concat(any) varchar2_b
EXPLAIN (COSTS FALSE) 
WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, 'あいう') = ' abcbaあいう' ORDER BY id;
EXPLAIN (COSTS FALSE) 
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, 'あいう') = ' abcbaあいう' ORDER BY id;
WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, 'あいう') = ' abcbaあいう' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, 'あいう') = ' abcbaあいう' ORDER BY id;

WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, '') = ' abcba' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, '') = ' abcba' ORDER BY id;

WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, NULL) = ' abcba' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, NULL) = ' abcba' ORDER BY id;

-- NG case
WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, NULL) = '' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, NULL) = '' ORDER BY id;

-- NG case
WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, NULL) IS NULL ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, NULL) IS NULL ORDER BY id;

WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat('あいう', val1) = 'あいう abcba' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat('あいう', val1) = 'あいう abcba' ORDER BY id;

WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat('', val1) = ' abcba' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat('', val1) = ' abcba' ORDER BY id;

WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(NULL, val1) = ' abcba' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(NULL, val1) = ' abcba' ORDER BY id;

-- NG case
WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(NULL, val1) = '' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(NULL, val1) = '' ORDER BY id;

-- NG case
WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(NULL, val1) IS NULL ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(NULL, val1) IS NULL ORDER BY id;

EXPLAIN (COSTS FALSE) 
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, '1.1e10'::real) = ' abcba1.1e+10' ORDER BY id;
WITH ft_varchar2_b_varchar AS (SELECT id, val1 FROM ft_varchar2_b_varchar)
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, '1.1e10'::real) = ' abcba1.1e+10' ORDER BY id;
SELECT id, val1 FROM ft_varchar2_b_varchar WHERE concat(val1, '1.1e10'::real) = ' abcba1.1e+10' ORDER BY id;

-- concat(any) nclob
EXPLAIN (COSTS FALSE) 
WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, 'あいう') = ' abcbaあいう' ORDER BY id;
EXPLAIN (COSTS FALSE) 
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, 'あいう') = ' abcbaあいう' ORDER BY id;
WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, 'あいう') = ' abcbaあいう' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, 'あいう') = ' abcbaあいう' ORDER BY id;

WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, '') = ' abcba' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, '') = ' abcba' ORDER BY id;

WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, NULL) = ' abcba' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, NULL) = ' abcba' ORDER BY id;

-- NG case
WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, NULL) = '' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, NULL) = '' ORDER BY id;

-- NG case
WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, NULL) IS NULL ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, NULL) IS NULL ORDER BY id;

WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat('あいう', val1) = 'あいう abcba' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat('あいう', val1) = 'あいう abcba' ORDER BY id;

WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat('', val1) = ' abcba' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat('', val1) = ' abcba' ORDER BY id;

WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(NULL, val1) = ' abcba' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(NULL, val1) = ' abcba' ORDER BY id;

-- NG case
WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(NULL, val1) = '' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(NULL, val1) = '' ORDER BY id;

-- NG case
WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(NULL, val1) IS NULL ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(NULL, val1) IS NULL ORDER BY id;

EXPLAIN (COSTS FALSE) 
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, '1.1e10'::real) = ' abcba1.1e+10' ORDER BY id;
WITH ft_nclob_text AS (SELECT id, val1 FROM ft_nclob_text)
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, '1.1e10'::real) = ' abcba1.1e+10' ORDER BY id;
SELECT id, val1 FROM ft_nclob_text WHERE concat(val1, '1.1e10'::real) = ' abcba1.1e+10' ORDER BY id;

-- concat(any) char_b
EXPLAIN (COSTS FALSE) 
WITH ft_char_b AS (SELECT id, val1 FROM ft_char_b)
SELECT id, val1 FROM ft_char_b WHERE concat(val1, 'あいう') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          あいう' ORDER BY id;
EXPLAIN (COSTS FALSE) 
SELECT id, val1 FROM ft_char_b WHERE concat(val1, 'あいう') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          あいう' ORDER BY id;
WITH ft_char_b AS (SELECT id, val1 FROM ft_char_b)
SELECT id, val1 FROM ft_char_b WHERE concat(val1, 'あいう') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          あいう' ORDER BY id;
SELECT id, val1 FROM ft_char_b WHERE concat(val1, 'あいう') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          あいう' ORDER BY id;

-- concat(any) char_c
EXPLAIN (COSTS FALSE) 
WITH ft_char_c AS (SELECT id, val1 FROM ft_char_c)
SELECT id, val1 FROM ft_char_c WHERE concat(val1, 'あいう') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          あいう' ORDER BY id;
EXPLAIN (COSTS FALSE) 
SELECT id, val1 FROM ft_char_c WHERE concat(val1, 'あいう') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          あいう' ORDER BY id;
WITH ft_char_c AS (SELECT id, val1 FROM ft_char_c)
SELECT id, val1 FROM ft_char_c WHERE concat(val1, 'あいう') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          あいう' ORDER BY id;
SELECT id, val1 FROM ft_char_c WHERE concat(val1, 'あいう') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          あいう' ORDER BY id;

-- concat(any) nchar
EXPLAIN (COSTS FALSE) 
WITH ft_nchar AS (SELECT id, val1 FROM ft_nchar)
SELECT id, val1 FROM ft_nchar WHERE concat(val1, '') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' ORDER BY id;
EXPLAIN (COSTS FALSE) 
SELECT id, val1 FROM ft_nchar WHERE concat(val1, '') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' ORDER BY id;
WITH ft_nchar AS (SELECT id, val1 FROM ft_nchar)
SELECT id, val1 FROM ft_nchar WHERE concat(val1, '') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' ORDER BY id;
SELECT id, val1 FROM ft_nchar WHERE concat(val1, '') = ' abcba                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ' ORDER BY id;

