\c contrib_regression_utf8

SET timezone = Japan;
SET DateStyle = iso,YMD;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
SET DateStyle = iso,DMY;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
SET DateStyle = iso,MDY;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;

SET DateStyle = sql,YMD;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
SET DateStyle = sql,DMY;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
SET DateStyle = sql,MDY;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;

SET DateStyle = postgres,YMD;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
SET DateStyle = postgres,DMY;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
SET DateStyle = postgres,MDY;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;

SET DateStyle = german,YMD;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
SET DateStyle = german,DMY;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
SET DateStyle = german,MDY;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;

SET timezone = UTC;
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;

SET timezone = 'America/New_York';
SELECT val1 FROM ft_date_date ORDER BY id;
SELECT val1 FROM ft_date_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamp ORDER BY id;
SELECT val1 FROM ft_timestamptz ORDER BY id;
SELECT val1 FROM ft_timestampltz ORDER BY id;
