\c contrib_regression_utf8

SET IntervalStyle = sql_standard;
SET DateStyle = postgres,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = postgres,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = postgres,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;

INSERT INTO rt_interval_ym (SELECT * FROM ft_interval_ym ORDER BY id);
INSERT INTO rt_interval_ds (SELECT * FROM ft_interval_ds ORDER BY id);
SET IntervalStyle = postgres;
SELECT * FROM rt_interval_ym;
SELECT * FROM rt_interval_ds;

SET IntervalStyle = postgres;
SET DateStyle = postgres,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = postgres,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = postgres,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;

SET IntervalStyle = postgres_verbose;
SET DateStyle = postgres,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = postgres,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = postgres,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;

SET IntervalStyle = iso_8601;
SET DateStyle = postgres,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = postgres,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = postgres,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = iso,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = sql,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,YMD;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,DMY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;
SET DateStyle = german,MDY;
SELECT * FROM ft_interval_ym ORDER BY id;
SELECT * FROM ft_interval_ds ORDER BY id;

